version: '3.4'

services:
  promethuse:
    image: ${DOCKER_REGISTRY-}promethuse
    build:
      context: .
      dockerfile: Promethuse/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+443;http://+80
    ports:
      - 8082:80
      - 8084:443

  grafana:
    image: grafana/grafana:master
    container_name: grafana
    ports:
      - "3100:3000" 
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  prometheusserver:
     image : prom/prometheus
     container_name : prometheus_grafprom
     restart: always
     ports: 
      - 9090:9090
     volumes:
      - ./Promethes/Prometheus.yml:/etc/Promethes/prometheus.yml:ro
      - ./Promethes/alert.rule.yml:/etc/Promethes/alert.rule.yml:ro 

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
     - ./alertmanager:/etc/alertmanager
    command:
     - '--config.file=/etc/alertmanager/alertmanager.yml'
     - '--storage.path=/alertmanager'
    ports:
      - 9093:9093



  
