version: '3.4'

services:
  promethuse:
    image: ${DOCKER_REGISTRY-}promethuse
    build:
      context: .
      dockerfile: Promethuse/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+443;http://+80
    ports:
      - 8082:80
      - 8084:443

  prometheusserver:
     image : prom/prometheus
     container_name : prometheus_grafprom
     restart: always
     ports: 
      - 9090:9090
     # volumes:
     #  - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  
