globle:
  scrape_intrval:  3s
  
  scrape_configs:
   -job_name: 'api-read-prometheus'
   scheme: http
   metrics_path: /metrics
   static_configs:
   - targets:
     - host.docker.internal:8082
  rule_files:
     - /etc/Promethes/alert.rule.yml
alerting:
 alertmanagers:
   - static_configs:
     - targets: ['alertmanager:9093']
    


